version: 2

project_name: kubectl-plugin

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
  

changelog:
  use: github
  sort: asc
  format: "{{ .SHA }}: {{ .Message }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).